import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";
import { CONSENT_AGREE, CONSENT_LINE } from "@/data/consent";
import { guarantee, monthly, priceCents, UPGRADE_CENTS, UPGRADE_WINDOW_DAYS } from "@/data/pricing";
import { SUPPORT_EMAIL } from "@/data/support";

// A standard online-course terms of service, fitted to this one: a
// six-week cohort bought with one payment, an AI coach whose feedback
// can be wrong, a no-questions 14-day refund, and - the part particular
// to Speak Better - learning from what students say as a condition of
// taking the course. Prices and windows are read from data/pricing.ts so
// the terms can never disagree with the checkout.

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms for taking Speak Better.",
};

const usd = (cents: number) => `$${(cents / 100).toLocaleString("en-US", { maximumFractionDigits: 0 })}`;

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      summary={
        <ul className="flex flex-col gap-1.5 [&_li]:ml-5 [&_li]:list-disc">
          <li>You pay once for six weeks of the course. It is not a subscription.</li>
          <li>Not for you? Ask within {guarantee.days} days and you get every cent back, for any reason.</li>
          <li>
            Taking the course means agreeing that transcripts of your speech - text, never video, under a number and
            not your name - are used to improve Speak Better and to track your progress.
          </li>
          <li>Coach is an AI. His feedback is usually helpful and sometimes wrong. It is coaching, not therapy or advice.</li>
          <li>Your recordings and words are yours. The lessons, videos and Coach are ours - for you to use, not to share.</li>
          <li>Be kind in the community. We can remove people who aren&apos;t.</li>
        </ul>
      }
    >
      <section>
        <h2>1. Agreeing to these terms</h2>
        <p>
          These terms are an agreement between you and Speak Better (&ldquo;we&rdquo;, &ldquo;us&rdquo;), which runs
          the Speak Better course, website and app (together, the &ldquo;Service&rdquo;). By buying a place, creating an
          account or using the Service, you agree to these terms and to our{" "}
          <Link href="/privacy" className="underline">
            Privacy Policy
          </Link>
          . If you don&apos;t agree, please don&apos;t use the Service.
        </p>
      </section>

      <section>
        <h2>2. What Speak Better is</h2>
        <p>
          Speak Better is an online public-speaking course. It includes short video lessons, on-camera challenges you
          record yourself completing, written and visual feedback on each recording from an AI coach called
          &ldquo;Coach&rdquo;, progress tracking, a community, and weekly live sessions. What is included depends on the
          tier you choose (Starter, Complete or VIP Ultimate), as described on our pricing page at the time you buy.
        </p>
        <p>
          Speak Better is an evolving system. We add, improve and sometimes change or remove features. We will not take
          away the core of what you paid for during your paid access.
        </p>
      </section>

      <section>
        <h2>3. Coach is an AI</h2>
        <p>
          Coach&apos;s feedback is generated by artificial intelligence. It is designed to help you practise and improve,
          but it can misunderstand, miss things or be wrong. Use your own judgement. Speak Better is education and
          coaching; it is not medical, psychological, speech-therapy, legal or professional advice. If you have a speech,
          voice or anxiety condition, please speak to a qualified professional.
        </p>
        <p>We don&apos;t promise any particular result - how much you improve depends on how you practise.</p>
      </section>

      <section>
        <h2>4. Your account</h2>
        <ul>
          <li>
            You must be at least 18 to buy a place. If you are 13 to 17, a parent or guardian must buy it for you and
            agree to these terms on your behalf. Speak Better is not for children under 13.
          </li>
          <li>Give accurate details, keep your login to yourself, and tell us if you think someone else has used it.</li>
          <li>One account is for one person. Sharing an account or a place in a cohort is not allowed.</li>
        </ul>
      </section>

      <section>
        <h2>5. Paying, and what you get for it</h2>
        <ul>
          <li>
            Each tier is a single payment, in US dollars, for six weeks of access as part of a cohort that starts and
            finishes together. It is not a subscription and does not renew.
          </li>
          <li>
            Founding-cohort prices are a discount on our standard prices, offered to a limited number of places in
            return for your honest feedback on the app. We may ask whether you&apos;d be willing to give a testimonial;
            that is always your choice.
          </li>
          <li>
            Starter students can upgrade to Complete within their first {UPGRADE_WINDOW_DAYS} days by paying the
            difference ({usd(UPGRADE_CENTS)}), for the rest of their six weeks.
          </li>
          <li>
            After the six weeks you may choose to stay on month to month (from {monthly.foundations} a month for
            Starter, {monthly.coached} for Complete). That is a separate, optional subscription that you can cancel at
            any time, effective at the end of the month you have paid for.
          </li>
          <li>
            Payments are handled by Stripe. We never see or store your full card details. Prices include any sales tax
            we are required to charge unless shown otherwise.
          </li>
        </ul>
        <p className="text-xs text-ink-faint">
          Current prices: Starter {usd(priceCents.foundations)}, Complete {usd(priceCents.coached)}, VIP Ultimate{" "}
          {usd(priceCents.founders)}.
        </p>
      </section>

      <section>
        <h2>6. The {guarantee.days}-day money-back guarantee</h2>
        <p>
          {guarantee.line} Email{" "}
          <a href={`mailto:${SUPPORT_EMAIL}`} className="underline">
            {SUPPORT_EMAIL}
          </a>{" "}
          within {guarantee.days} days of paying and we will refund you in full to your original payment method -
          usually within 5 to 10 working days - and close your access. If you are on VIP Ultimate and your printed
          deck and book have already been sent, they are yours to keep. After {guarantee.days} days, payments are not
          refundable, except where the law says otherwise or we cancel your cohort.
        </p>
      </section>

      <section>
        <h2>7. How Speak Better learns - a condition of the course</h2>
        <p>
          <b className="text-ink">{CONSENT_AGREE}</b>
        </p>
        <p>{CONSENT_LINE}</p>
        <p>
          This is part of what Speak Better is, so it is a condition of using it. You will be asked to confirm it when
          you start. If you don&apos;t agree, Speak Better isn&apos;t the right fit - and if you have already paid, the{" "}
          {guarantee.days}-day guarantee gives you your money back. The{" "}
          <Link href="/privacy" className="underline">
            Privacy Policy
          </Link>{" "}
          explains exactly what is kept, how, and for how long.
        </p>
      </section>

      <section>
        <h2>8. Your recordings and your words</h2>
        <p>
          You own what you record and write. So that we can run the Service, you give us permission to process your
          recordings to produce your feedback (after which the recordings are deleted, as the Privacy Policy explains),
          and to use transcripts, feedback, scores and ratings, without your name, to track your progress and to improve
          Speak Better and Coach - including teaching and testing Coach with examples. That permission continues for
          de-identified text after your access ends, because by then it cannot be tied back to you.
        </p>
        <p>
          We will never publish your recording, your face, your name or your words as a testimonial or in marketing
          without asking you first.
        </p>
      </section>

      <section>
        <h2>9. The community and live sessions</h2>
        <ul>
          <li>Be kind and constructive. Everyone here is practising something that feels exposing.</li>
          <li>No harassment, hate, sexual content, spam, or selling.</li>
          <li>
            Don&apos;t record, screenshot or share other students, their takes or their messages outside Speak Better
            without their permission.
          </li>
          <li>Things you post in community spaces can be seen by the other students there.</li>
        </ul>
        <p>We may remove content, or suspend or end an account, that breaks these rules.</p>
      </section>

      <section>
        <h2>10. Our content</h2>
        <p>
          The lessons, videos, challenges, cards, method, Coach and everything else we provide belong to us or the people
          who license them to us. While you have access, you may use them for your own personal learning. You may not
          copy, download (other than where we offer it), resell, share logins, publish, scrape, or use them to build or
          train a competing product or AI model.
        </p>
      </section>

      <section>
        <h2>11. Fair use of the Service</h2>
        <p>
          Don&apos;t misuse the Service: no trying to break, overload or get around its security; no automated access;
          no uploading anything unlawful or anything you don&apos;t have the right to share; and no recording other
          people without their consent.
        </p>
      </section>

      <section>
        <h2>12. Availability</h2>
        <p>
          We work hard to keep Speak Better running, but it is provided &ldquo;as is&rdquo; and &ldquo;as
          available&rdquo;. There may be interruptions, and features that depend on other companies (such as video
          hosting or the AI behind Coach) may occasionally be unavailable. If a live session has to move, we will tell
          you and offer another time or a recording.
        </p>
      </section>

      <section>
        <h2>13. Limits on our liability</h2>
        <p>
          To the fullest extent the law allows, we are not liable for indirect or consequential losses, and our total
          liability to you for anything to do with the Service is limited to the amount you paid us in the twelve
          months before the claim. Nothing in these terms limits liability that cannot be limited by law, or your rights
          as a consumer.
        </p>
      </section>

      <section>
        <h2>14. Ending your access</h2>
        <p>
          You can stop using Speak Better at any time and ask us to delete your account. We may suspend or end access if
          you seriously or repeatedly break these terms; if we do so without good reason, we will refund the unused part
          of your payment.
        </p>
      </section>

      <section>
        <h2>15. Changes to these terms</h2>
        <p>
          If we change these terms we will update the date at the top, and tell you about any important change before it
          affects you. The terms in place when you bought your place apply to that purchase.
        </p>
      </section>

      <section>
        <h2>16. Contact</h2>
        <p>
          Questions about these terms:{" "}
          <a href={`mailto:${SUPPORT_EMAIL}`} className="underline">
            {SUPPORT_EMAIL}
          </a>
          .
        </p>
      </section>
    </LegalPage>
  );
}
